language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - sudo apt-get update
    - sudo apt-get install -y libav-tools sox
    - "pip install -e .[dev,ci]"

script:
    - flake8
    - pytest
