language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - sudo apt-get update
    - sudo apt-get install -y libav-tools sox
    - "pip install -e .[dev,ci]"

script:
    - flake8
    - pytest --cov=./ --cov-report xml
    - curl https://deepsource.io/cli | sh
    - export DEEPSOURCE_DSN=https://3d33688841cb4a6c9929988d8659e60c@deepsource.io
    - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
